# Generated by Django 3.2 on 2023-05-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('isbn', models.CharField(blank=True, max_length=100, null=True)),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('page_number', models.IntegerField()),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='cover_photos')),
            ],
        ),
    ]
