# Generated by Django 3.2 on 2023-05-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Library', '0002_create_review_and_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='book_id',
            new_name='book',
        ),
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
