# Generated by Django 3.2 on 2023-05-24 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Library', '0003_auto_20230524_0350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author_name',
            new_name='author',
        ),
    ]
