# Generated by Django 3.2.19 on 2023-05-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Library', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_type',
            field=models.CharField(choices=[('U', 'User'), ('A', 'Admin'), ('M', 'Moderator')], default='U', max_length=1),
        ),
    ]
