# Generated by Django 3.2.19 on 2023-05-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Library', '0010_auto_20230526_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_status',
            field=models.CharField(choices=[('PS', 'Published'), ('RJ', 'Rejected'), ('PD', 'Pending')], default='U', max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_type',
            field=models.CharField(choices=[('A', 'Admin'), ('U', 'User'), ('M', 'Moderator')], default='U', max_length=1),
        ),
    ]
