# Generated by Django 3.2.19 on 2023-05-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Library', '0017_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_type',
            field=models.CharField(choices=[('A', 'Admin'), ('M', 'Moderator'), ('U', 'User')], default='U', max_length=1),
        ),
    ]
