# Generated by Django 3.2.19 on 2023-05-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Library', '0020_auto_20230528_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='created_by',
            new_name='added_by',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_status',
            field=models.CharField(choices=[('Published', 'Published'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=9),
        ),
    ]
